# Generated by Django 3.1.1 on 2021-04-28 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.area')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileId', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('itemId', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('current_value', models.IntegerField()),
                ('interval_of_days', models.IntegerField()),
                ('increasing_ratio_in_percentage', models.IntegerField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('image', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('lentTo', models.CharField(blank=True, max_length=100, null=True)),
                ('lentToFriend', models.BooleanField(blank=True, default=False, null=True)),
                ('extraDetails', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.category')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.container')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AddField(
            model_name='category',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.container'),
        ),
        migrations.AddField(
            model_name='area',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.place'),
        ),
        migrations.AddField(
            model_name='area',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accountName', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
