# Generated by Django 3.1.1 on 2021-04-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210428_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
