# Generated by Django 3.1.2 on 2021-05-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210429_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='current_value',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='value',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
