# Generated by Django 3.1.2 on 2021-05-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210501_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='current_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
